In [1]:
import pandas as pd

# 문제1. vaccine.csv 데이터를 데이터프레임으로 읽기

In [2]:
df = pd.read_csv("./data/vaccine.csv")

In [3]:
df.head()

         date  subject  day1num  day1sum  day1rate  day2num  day2sum  day2rate
0  2021.10.16  9505868    10673  7562283      79.6    66910  6191341      65.1
1  2021.10.15  9505868    14556  7551829      79.4   133580  6124432      64.4
2  2021.10.14  9505868     9609  7536654      79.3    94569  5989111      63.0
3  2021.10.13  9505868     9804  7526430      79.2    77503  5893191      62.0
4  2021.10.12  9505868    17274  7516070      79.1   110204  5814018      61.2

# 문제2. 데이터프레임에서 필요 없는 열을 삭제하기

- 삭제할 열 : day1sum, day1rate, day2sum, day2rate

In [5]:
df = df.drop(["day1sum", "day1rate", "day2sum", "day2rate"], axis = 1)

In [6]:
df.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

# 문제3. 데이터프레임의 기초통계량을 확인하기

In [7]:
df.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

# 문제4. day1num과 day2num의 월별 평균을 출력하기

In [8]:
df.head()

         date  subject  day1num  day2num
0  2021.10.16  9505868    10673    66910
1  2021.10.15  9505868    14556   133580
2  2021.10.14  9505868     9609    94569
3  2021.10.13  9505868     9804    77503
4  2021.10.12  9505868    17274   110204

In [10]:
df.tail()

           date  subject  day1num  day2num
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

In [9]:
df.shape

(179, 4)

In [11]:
df.dtypes

date       object
subject     int64
day1num     int64
day2num     int64
dtype: object

In [17]:
# lambda, split 활용 month 열 분리
df["month"] = df["date"].map(lambda x: x.split(".")[1])

In [20]:
# str 메서드 활용 month 열 분리
df["month"] = df["date"].str.split(".").str.get(1)

In [24]:
# date 자료형을 datetime 타입으로 변경
df["date"] = pd.to_datetime(df["date"], format = "%Y.%m.%d")

In [25]:
df.dtypes

date       datetime64[ns]
subject             int64
day1num             int64
day2num             int64
month              object
dtype: object

In [27]:
# lambda, datetime 타입 활용
df["month"] = df["date"].map(lambda x: x.month)

In [31]:
df["month"] = df["date"].dt.month

In [32]:
df.head()

        date  subject  day1num  day2num  month
0 2021-10-16  9505868    10673    66910     10
1 2021-10-15  9505868    14556   133580     10
2 2021-10-14  9505868     9609    94569     10
3 2021-10-13  9505868     9804    77503     10
4 2021-10-12  9505868    17274   110204     10

In [33]:
df.groupby("month")[["day1num", "day2num"]].mean()

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000