In [1]:
import pandas as pd
import numpy as np

# 문제1. 데이터프레임을 iris 변수로 읽기

In [2]:
iris = pd.read_csv("./data/iris.csv")

In [3]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

# 아래 코드를 실행해주세요

In [4]:
iris.iloc[10:30,2:3] = np.nan

# 문제2. 데이터프레임에 누락값이 있는지 확인

In [5]:
iris.isnull().sum()

SepalLength     0
SepalWidth      0
PetalLength    20
PetalWidth      0
Species         0
dtype: int64

# 문제3. 결측치에 1 채워넣기

In [6]:
iris = iris.fillna(1)

In [7]:
iris.isnull().sum()

SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64

# 문제4. Species 컬럼 삭제하기

In [8]:
iris = iris.drop("Species", axis = 1)

In [9]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

# 아래 코드를 실행해주세요

In [10]:
iris.iloc[0:3 ,:] = np.nan

# 문제5. 결측치가 존재하는 행 삭제하기

In [11]:
iris.isnull().sum()

SepalLength    3
SepalWidth     3
PetalLength    3
PetalWidth     3
dtype: int64

In [12]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          NaN         NaN          NaN         NaN
1          NaN         NaN          NaN         NaN
2          NaN         NaN          NaN         NaN
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [13]:
iris = iris.dropna(axis = 0)

In [14]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2
5          5.4         3.9          1.7         0.4
6          4.6         3.4          1.4         0.3
7          5.0         3.4          1.5         0.2

# 문제6. 인덱스가 0부터 시작하도록 재설정

In [17]:
iris = iris.reset_index(drop = True)

In [18]:
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          4.6         3.1          1.5         0.2
1          5.0         3.6          1.4         0.2
2          5.4         3.9          1.7         0.4
3          4.6         3.4          1.4         0.3
4          5.0         3.4          1.5         0.2