# 판다스 자료구조

- 분석을 위해 수집하는 데이터는 형태나 속성이 매우 다양함
    - 서로 다른 형식을 갖는 여러 종류의 데이터를 컴퓨터가 이해할 수 있도록 동일한 형식을 갖는 구조로 통합할 필요가 있음

- 판다스 데이터의 형식
    - 시리즈(Series)
        - 1차원 배열
     
    - 데이터프레임(DataFrame)
        - 2차원 배열

## 시리즈(Series)

<img src="./image/series.jpg" width=400 height=300>

- 데이터가 순차적으로 나열된 1차원 배열

- 각 인덱스(index)는 값(value)과 1:1 대응이 됨
    - 이런 관점에서 키와 값이 짝을 이루는 딕셔너리와 비슷한 구조라고도 볼 수 있음
    - 시리즈에서 인덱스는 데이터 값의 위치를 나타내는 이름표 역할을 수행

In [1]:
# 라이브러리 코드
import pandas as pd
import numpy as np
import seaborn as sns

### 시리즈 생성

In [2]:
# 딕셔너리 생성
dict_data = {"a" : 1, "b" : 2, "c" : 3}

In [3]:
# 딕셔너리를 판다스 시리즈로 변환
sr = pd.Series(dict_data)

In [4]:
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

In [5]:
# 시리즈를 구성하는 데이터 값의 자료형 확인
sr.dtypes

dtype('int64')

In [6]:
# 시리즈의 인덱스 배열
sr.index

Index(['a', 'b', 'c'], dtype='object')

In [7]:
# 시리즈의 값 배열
sr.values

array([1, 2, 3])

- 리스트를 시리즈로 변환하면 인덱스로 변환될 값이 없음
    - 인덱스가 별도로 지정되지 않으면 정수형 위치 인덱스(0, 1, 2, ...)가 자동으로 지정

In [8]:
# 리스트를 시리즈로 변환
list_data = ["2026", 3.14, "ABC", 100, True]

In [9]:
sr = pd.Series(list_data)

In [10]:
print(sr)

0    2026
1    3.14
2     ABC
3     100
4    True
dtype: object

In [11]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
sr.values

array(['2026', 3.14, 'ABC', 100, True], dtype=object)

In [13]:
# 튜플을 시리즈로 변환
tup_data = ("영인", "2010-05-01", "여", True)

In [16]:
sr = pd.Series(tup_data, index = ["이름", "생년월일", "성별", "학생여부"])

In [17]:
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

### 원소 선택

- 인덱스를 이용하여 원소를 선택할 수 있음
    - 하나의 원소를 선택
    - 여러 원소를 한꺼번에 선택
    - 인덱스 범위를 지정하여 원소를 선택
        - 슬라이싱과 유사

- 정수형 위치 인덱스는 대괄호 안에 위치를 나타내는 숫자를 입력

- 인덱스 이름은 따옴표와 함께 입력

In [19]:
# 원소 1개 선택
print(sr["이름"])

영인

In [21]:
# 여러 원소 선택(인덱스 리스트 활용)
print(sr[["생년월일", "성별"]])

생년월일    2010-05-01
성별               여
dtype: object

In [22]:
# 여러 원소 선택(인덱스 범위 지정)
# 인덱스 이름을 사용하면 범위의 끝이 포함
print(sr["생년월일" : "성별"])

생년월일    2010-05-01
성별               여
dtype: object

## 데이터프레임

<img src="./image/dataframe.jpg" width=400 height=300>

- 행과 열로 이루어진 2차원 배열
- 여러 개의 시리즈들이 모여서 데이터프레임을 구성
    - 데이터프레임의 열은 각각 시리즈 객체
    - 여러 개의 시리즈들이 같은 행 인덱스를 기준으로 결합된 2차원 행렬

- 행과 열을 나타내기 위해 두 가지 종류의 주소를 사용
    - 행 인덱스
        - 개별 관측 대상에 대한 다양한 속성 데이터들의 모음
            - 레코드(record)
    
    - 열 이름
        - 공통의 속성을 갖는 일련의 데이터
    
    - 예) 주식 종목 데이터
        - 행 : 각 주식 종목에 대한 관측값
        - 열 : 회사 이름, 총 주식 수, 액면가 등

### 데이터프레임 생성

- 동일한 길이의 1차원 배열 여러 개가 필요

In [23]:
dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6]
}

In [24]:
# 딕셔너리를 데이터프레임으로 변환
df = pd.DataFrame(dict_data)

In [25]:
df

   c0  c1
0   1   4
1   2   5
2   3   6

In [26]:
type(df)

pandas.core.frame.DataFrame

### 행 인덱스 / 열 이름 설정

```
pandas.DataFrame(2차원 배열, index = 행 인덱스 배열, columns = 열 이름 배열)
```

In [27]:
df = pd.DataFrame([
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
])

In [28]:
df

    0  1    2
0  15  남  덕영중
1  17  여  수리중

In [29]:
df = pd.DataFrame([
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
], index = ["준서", "예은"], columns = ["나이", "성별", "학교"])

In [30]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [31]:
# 행 인덱스
df.index

Index(['준서', '예은'], dtype='object')

In [33]:
# 열 이름
df.columns

Index(['나이', '성별', '학교'], dtype='object')

In [34]:
# 데이터프레임 값 확인
df.values

array([[15, '남', '덕영중'],
       [17, '여', '수리중']], dtype=object)

#### 행 인덱스 / 열 이름 변경

```
데이터프레임명.index = 새 행 인덱스 배열
데이터프레임명.columns = 새 열 이름 배열
```

In [35]:
df.index = ["학생1", "학생2"]

In [36]:
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [37]:
# 열 이름 변경
df.columns = ["연령", "남녀", "소속"]

In [38]:
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

#### 행 인덱스 / 열 이름 변경(rename 메소드 활용)

```
데이터프레임명.rename(index = {기존 인덱스 : 새 인덱스, ...}, columns = {기존 열 이름 : 새 열 이름, ...})
```

- rename 메소드는 비파괴적인 명령어이기 때문에 원본 데이터를 변경하지 않습니다!

In [41]:
df.rename(columns = {"연령" : "나이", "소속" : "학교"})

     나이 남녀   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [42]:
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [43]:
# 원본 객체를 수정하려면 inplace = True 옵션을 사용
df.rename(columns = {"연령" : "나이", "소속" : "학교"}, inplace = True)

In [44]:
df

     나이 남녀   학교
학생1  15  남  덕영중
학생2  17  여  수리중

### 행 / 열 삭제

- drop() 메소드
    - axis = 0 : 행 삭제
    - axis = 1 : 열 삭제
    
    - 동시에 여러 행 또는 여러 열 삭제
        - 리스트 형태로 입력
    
    - 기존 객체를 변경하지 않고 새로운 객체를 반환
        - 원본 객체를 직접 변경하기 위해서는 inplace = True 옵션 사용

In [45]:
exam_data = {"수학" : [90, 80, 70],
             "영어" : [98, 89, 95],
             "음악" : [85, 95, 100],
             "체육" : [100, 90, 90]}

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])

In [46]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [47]:
df2 = df.copy()

#### 행 삭제

In [48]:
df2.drop("우현")

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [49]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [50]:
df2.drop("우현", inplace = True) # axis = 0이 초기값

In [51]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [52]:
df3 = df.copy()

In [53]:
df3

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [54]:
df3.drop(["우현", "인아"], axis = 0)

    수학  영어  음악   체육
서준  90  98  85  100

In [55]:
df3

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [56]:
df3 = df3.drop(["우현", "인아"], axis = 0)

In [57]:
df3

    수학  영어  음악   체육
서준  90  98  85  100

#### 열 삭제

In [58]:
df4 = df.copy()

In [59]:
df4

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [60]:
df4 = df4.drop("수학", axis = 1)

In [61]:
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [62]:
df5 = df.copy()

In [63]:
df5

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [64]:
df5.drop(["영어", "음악"], axis = 1)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

### 행 선택

- loc
    - 인덱스 이름을 사용

- iloc
    - 정수형 위치 인덱스를 사용

In [65]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

#### 하나의 행 선택

In [66]:
label1 = df.loc["서준"]
position1 = df.iloc[0]

In [67]:
label1

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [68]:
position1

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

#### 2개 이상의 행 선택

In [73]:
label2 = df.loc[["서준", "우현"]]
position2 = df.iloc[[0, 1]]

In [74]:
label2

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [75]:
position2

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

#### 행 인덱스의 범위를 지정하여 행 선택

In [76]:
label3 = df.loc["서준" : "우현"]
position3 = df.iloc[0 : 1]

In [77]:
label3

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [78]:
position3

    수학  영어  음악   체육
서준  90  98  85  100

### 열 선택

- 열 데이터를 1개만 선택하는 경우
    - 대괄호 안에 열 이름을 따옴표와 함께 입력
    - 도트(.) 다음에 열 이름을 입력
        - 열 이름이 문자열일 경우에만 가능

- 여러 열을 선택하는 경우
    - 대괄호 안에 열 이름 리스트 입력
    - 리스트의 원소로 열 이름이 하나만 있는 경우에는 시리즈가 아니라 데이터프레임이 됨

In [79]:
exam_data = {"이름" : ["서준", "우현", "인아"],
             "수학" : [90, 80, 70],
             "영어" : [98, 89, 95],
             "음악" : [85, 95, 100],
             "체육" : [100, 90, 90]}

df = pd.DataFrame(exam_data)

In [80]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [81]:
# 수학 점수 데이터만 선택
df["수학"]

0    90
1    80
2    70
Name: 수학, dtype: int64

In [82]:
# 영어 점수 데이터만 선택
df.영어

0    98
1    89
2    95
Name: 영어, dtype: int64

In [83]:
# 2개 이상의 열 추출
df[["음악", "체육"]]

    음악   체육
0   85  100
1   95   90
2  100   90

In [84]:
# 수학 점수 데이터만 데이터프레임으로 추출
df[["수학"]]

   수학
0  90
1  80
2  70

### 원소 선택

- 데이터프레임의 행 인덱스와 열 이름을 [행, 열] 형식의 2차원 좌표로 입력하여 원소를 지정

- 원소가 위치하는 행과 열의 좌표를 입력하면 해당 위치의 원소가 반환

- 1개의 행과 2개 이상의 열 또는 2개 이상의 행과 1개의 열을 선택하면 시리즈 객체가 반환

- 2개 이상의 행과 2개 이상의 열을 선택하면 데이터프레임 객체를 반환

```
데이터프레임명.loc[행 인덱스, 열 이름]
데이터프레임명.iloc[행 번호, 열 번호]
```

In [88]:
# set_index() : 특정 컬럼을 새로운 인덱스로 지정
df = df.set_index("이름")

In [89]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [90]:
# 서준의 음악 점수
a = df.loc["서준", "음악"]
b = df.iloc[0, 2]

print(a)
print(b)

85
85

In [101]:
# 서준의 음악, 체육 점수
c = df.loc["서준", ["음악", "체육"]]

# 동일 코드
# c = df.loc["서준", "음악" : "체육"]

print(c)

음악     85
체육    100
Name: 서준, dtype: int64

In [102]:
# 나열의 의미가 생기게 되면 하나의 행만을 포함해도 데이터프레임으로 반환
d = df.loc[["서준"], ["음악", "체육"]]
print(d)

    음악   체육
이름
서준  85  100

In [103]:
e = df.iloc[0, [2, 3]]

# 동일 코드
# e = df.iloc[0, [2:]]

print(e)

음악     85
체육    100
Name: 서준, dtype: int64

In [104]:
f = df.iloc[[0], [2, 3]]
print(f)

    음악   체육
이름
서준  85  100

In [107]:
# 서준, 우현의 음악, 체육 점수
g = df.loc[["서준", "우현"], ["음악", "체육"]]

# 동일 코드
# g = df.loc["서준" : "우현", "음악" : "체육"]

print(g)

    음악   체육
이름
서준  85  100
우현  95   90

In [108]:
h = df.iloc[[0, 1], [2, 3]]

# 동일 코드
# h = df.iloc[:2, 2:]

print(h)

    음악   체육
이름
서준  85  100
우현  95   90

### 열 추가

```
데이터프레임["추가하려는 열 이름"] = 데이터 값 또는 배열
```

- 단일 값을 입력하면 모든 행에 동일한 값이 입력됨

In [110]:
exam_data = {"이름" : ["서준", "우현", "인아"],
             "수학" : [90, 80, 70],
             "영어" : [98, 89, 95],
             "음악" : [85, 95, 100],
             "체육" : [100, 90, 90]}

df = pd.DataFrame(exam_data)

In [111]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [112]:
# 국어 점수 추가
df["국어"] = 80

In [113]:
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

### 행 추가

- 추가하려는 행 이름과 데이터 값을 loc를 사용하여 입력

```
데이터프레임.loc["새로운 행 이름"] = 데이터 값 또는 배열
```

In [114]:
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [115]:
df.loc[3] = 0

In [116]:
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80
3   0   0   0    0    0   0

In [117]:
df.loc[4] = ["동규", 90, 80, 70, 60, 50]

In [118]:
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80
3   0   0   0    0    0   0
4  동규  90  80   70   60  50

### 원소 값 변경

- 데이터프레임의 특정 원소를 선택하고 새로운 데이터 값을 지정

- 원소 1개를 선택하거나 여러 원소를 선택하여 한꺼번에 값을 변경할 수 있음

In [123]:
exam_data = {"이름" : ["서준", "우현", "인아"],
             "수학" : [90, 80, 70],
             "영어" : [98, 89, 95],
             "음악" : [85, 95, 100],
             "체육" : [100, 90, 90]}

df = pd.DataFrame(exam_data)
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [124]:
# 서준의 체육 점수 수정
df.iloc[0, 3]

np.int64(100)

In [125]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [126]:
df.loc["서준", "체육"] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [127]:
# 서준의 음악, 체육 점수 변경
df.loc["서준", ["음악", "체육"]]

음악    85
체육    90
Name: 서준, dtype: int64

In [128]:
df.loc["서준", ["음악", "체육"]] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [132]:
df.loc["서준", ["음악", "체육"]] = (100, 60)

In [133]:
df

    수학  영어   음악  체육
이름
서준  90  98  100  60
우현  80  89   95  90
인아  70  95  100  90

### 행, 열의 위치 변경하기

- 데이터프레임의 행과 열을 서로 맞바꾸는 방법
    - 열 이름이 행 인덱스로 이동하고 행 인덱스가 열 이름으로 이동

- 선형대수학의 전치행렬과 같은 개념

- 전치의 결과로 새로운 객체를 반환
    - 기존의 객체를 변경하고 싶다면 기존 객체에 새로운 객체를 재할당 해주는 과정이 필요

```
데이터프레임.transpose()
또는
데이터프레임.T
```

In [134]:
df

    수학  영어   음악  체육
이름
서준  90  98  100  60
우현  80  89   95  90
인아  70  95  100  90

In [137]:
# df를 전치 (transpose 활용)
df = df.transpose()
df

이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악  100  95  100
체육   60  90   90

In [138]:
# df를 전치 (클래스 속성 활용)
df = df.T
df

    수학  영어   음악  체육
이름
서준  90  98  100  60
우현  80  89   95  90
인아  70  95  100  90

# 인덱스 활용

## 특정 열을 행 인덱스로 설정

- set_index()
    - 데이터프레임의 특정 열을 행 인덱스로 설정
 
- 새로운 데이터프레임 객체를 반환

- set_index() 메소드를 사용하여 행 인덱스를 새로 지정하면 기존 행 인덱스는 삭제됨

In [140]:
exam_data = {"이름" : ["서준", "우현", "인아"],
             "수학" : [90, 80, 70],
             "영어" : [98, 89, 95],
             "음악" : [85, 95, 100],
             "체육" : [100, 90, 90]}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [141]:
# 특정 열을 행 인덱스로 설정
ndf = df.set_index("이름")
ndf

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [142]:
ndf2 = ndf.set_index("음악")
ndf2

     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90

In [143]:
ndf3 = ndf.set_index(["수학", "음악"])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

#### 행 인덱스 초기화

- reset_index()
    - 행 인덱스를 정수형 위치 인덱스로 초기화
    - 기존 행 인덱스는 열로 이동

- 새로운 데이터프레임 객체를 반환

In [144]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])

In [145]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [146]:
df.reset_index()

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [147]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

## 행 인덱스를 기준으로 데이터프레임 정렬

- sort_index()
    - 행 인덱스를 기준으로 데이터프레임의 값을 정렬
 
    - ascending 옵션을 사용하여 정렬 옵션(오름차순|내림차순) 설정
        - ascending = False : 내림차순
        - ascending = True : 오름차순
        - 기본값은 오름차순

- 새롭게 정렬된 데이터프레임을 반환

In [148]:
# 내림차순으로 행 인덱스 정렬
df.sort_index(ascending = False)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

#### 특정 열의 데이터 값을 기준으로 데이터프레임 정렬

- sort_values()
    - 특정 열의 데이터를 기준으로 데이터프레임 정렬
 
    - ascending 옵션 사용하여 정렬 옵션 설정
        - 기본값은 오름차순

In [149]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [150]:
# c1 열을 기준으로 내림차순 정렬
df.sort_values(by = "c1", ascending = False)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

# 산술연산

- 판다스 객체의 산술연산은 내부적으로 3단계 프로세스
    1. 행/열 인덱스를 기준으로 모든 원소를 정렬
    2. 동일한 위치에 있는 원소끼리 일대일로 대응
    3. 일대일 대응이 되는 원소끼리 연산 처리
        - 대응되는 원소가 없으면 NaN 처리

## 시리즈 연산

### 시리즈와 숫자

- 시리즈 객체에 숫자를 더하면 시리즈의 개별 원소에 각각 숫자를 더하고 계산한 결과를 시리즈 객체로 반환

- 덧셈, 뺄셈, 곱셈, 나눗셈 모두 가능

In [2]:
student1 = pd.Series({"국어" : 100, "영어" : 80, "수학" : 90})

In [3]:
student1

국어    100
영어     80
수학     90
dtype: int64

In [4]:
percentage = student1 / 100

In [5]:
percentage

국어    1.0
영어    0.8
수학    0.9
dtype: float64

### 시리즈와 시리즈

- 같은 인덱스를 가진 원소끼리 계산

- 인덱스에 연산 결과를 매칭하여 새 시리즈를 반환

In [6]:
student2 = pd.Series({"수학" : 80, "국어" : 90, "영어" : 80})

In [7]:
student1

국어    100
영어     80
수학     90
dtype: int64

In [8]:
student2

수학    80
국어    90
영어    80
dtype: int64

In [9]:
student1 + student2

국어    190
수학    170
영어    160
dtype: int64

- 인덱스로 주어진 과목명의 순서가 다르지만 판다스는 같은 과목명을 찾아 정렬한 후 같은 과목명의 점수끼리 연산을 수행

- 연산을 하는 두 시리즈의 원소 개수가 다르거나 인덱스 값이 다른 경우
    - 정상적으로 연산 처리 불가능
        - NaN

In [10]:
# NaN 값이 있는 시리즈 연산
student1 = pd.Series({"국어" : np.nan, "영어" : 80, "수학" : 90})
student2 = pd.Series({"수학" : 80, "국어" : 90})

In [11]:
student1

국어     NaN
영어    80.0
수학    90.0
dtype: float64

In [12]:
student2

수학    80
국어    90
dtype: int64

In [13]:
student1 + student2

국어      NaN
수학    170.0
영어      NaN
dtype: float64

### 연산 메소드

- 결과가 NaN으로 반환되는 상황을 피하기 위해 연산 메소드에 fill_value 옵션을 설정

In [14]:
sr_add = student1.add(student2, fill_value = 0) # 덧셈
sr_sub = student1.sub(student2, fill_value = 0) # 뺄셈
sr_mul = student1.mul(student2, fill_value = 0) # 곱셈
sr_div = student1.div(student2, fill_value = 0) # 나눗셈

In [15]:
result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div], index = ["덧셈", "뺄셈", "곱셈", "나눗셈"])

In [16]:
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

## 데이터프레임 연산

- 데이터프레임은 여러 시리즈가 모인 것이므로 시리즈 연산을 확장하는 개념

- 행/열 인덱스를 기준으로 정렬하고 일대일 대응되는 원소끼리 연산 처리

### 데이터프레임과 숫자

- 모든 원소에 숫자를 계산
- 기존 데이터프레임의 형태를 그대로 유지한 채 원소 값만 새로운 계산으로 변경됨
- 새로운 데이터프레임 객체로 반환

In [17]:
# titanic 데이터셋에서 age, fare 2개 열을 선택
titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
df = titanic[["age", "fare"]]

In [21]:
df.head() # 첫 5개의 행만 표시

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [22]:
addition = df + 10

In [23]:
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [24]:
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

### 데이터프레임과 데이터프레임

- 각 데이터프레임의 같은 행, 같은 열 위치에 있는 원소끼리 계산

- 동일한 위치의 원소끼리 계산한 결과값을 원래 위치에 다시 입력하여 데이터프레임을 생성

- 데이터프레임 ㅈ우 어느 한쪽에 원소가 존재하지 않거나 NaN이면 연산 결과는 NaN 처리

In [25]:
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [26]:
subtraction = addition - df

In [27]:
subtraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0