# 데이터 전처리

- 데이터 분석의 정확도는 분석 데이터의 품질에 의해 좌우됨
    - 데이터 품질을 높이기 위해 누락 데이터, 중복 데이터 등의 오류를 수정하고 분석 목적에 맞게 변형하는 과정이 필요
    - 수집한 데이터를 분석에 적합하도록 만드는 과정을 전처리라고 함

# 누락 데이터 처리

- 데이터프레임에는 여러가지 이유로 원소 데이터 값이 누락되는 경우가 종종 있음
    - 데이터를 파일로 입력할 때 빠트리거나 파일 형식을 변환하는 과정에서 데이터가 소실되는 등의 원인
 
- 일반적으로 누락 데이터를 NaN(Not a Number)으로 표시

- 머신러닝 분석 모형에 데이터를 입력하기 전에 누락 데이터를 제거하거나 다른 적절한 값으로 대체하는 과정이 필요
    - 누락 데이터가 많아지면 데이터의 품질이 떨어지고, 머신러닝 분석 알고리즘을 왜곡하는 현상이 발생
 
- 누락 데이터를 찾는 메소드
    - 누락 데이터를 True로 반환, 유효한 데이터를 False로 반환
        - isnull() / isna()
     
    - 누락 데이터를 False로 반환
        - notnull() / notna()

## 누락 데이터 확인

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
# titanic 데이터셋 가져오기
df = sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.shape

(891, 15)

In [5]:
df.describe(include = "all")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [9]:
df["deck"].value_counts(dropna = False)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [11]:
# isnull() 메서드로 누락 데이터 찾기
df.isnull().sum(axis = 0)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 누락 데이터 제거

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
# NaN 값이 500개 이상인 열을 모두 삭제
df_thresh = df.dropna(axis = 1, thresh = 500)

In [5]:
df_thresh.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [6]:
# age 열에 나이 데이터가 없는 모든 행을 삭제
df_age = df.dropna(axis = 0, subset = "age")

In [7]:
df_age.shape

(714, 15)

In [8]:
df.shape

(891, 15)

- dropna()
    - subset : 특정 열에 NaN 값이 있는 모든 행이 대상이 됨
    - how
        - how = "any" : NaN 값이 하나라도 존재하면 삭제
        - how = "all" : 모든 데이터가 NaN값일 경우에만 삭제
        - 기본값은 any

## 누락 데이터 치환

- 누락 데이터를 무작정 삭제한다면 데이터가 지나치게 줄어들 수 있음
    - 분석 정확도는 데이터의 품질 외에도 제공되는 데이터의 양에 상당한 영향을 받음
    - 데이터 중에 일부 누락되어 있더라도 나머지 데이터를 최대한 활용해야함

- 누락 데이터를 대체할 값
    - 데이터의 분포와 특성을 잘 나타낼 수 있는 값
        - 평균값
        - 최빈값 등
 
    - fillna() 메소드로 처리
        - 새로운 객체를 반환
     
    - ffill() / bfill() 메소드
        - 데이터셋에서 서로 이웃하고 있는 데이터끼리는 유사성을 가질 가능성이 높음
            - 앞이나 뒤에서 이웃하고 있는 값으로 치환하는 경우도 있음
         
        - ffill() : NaN이 있는 행의 직전 행에 있는 값으로 치환
     
        - bfill() : NaN이 있는 행의 바로 다음 행에 있는 값으로 치환

In [10]:
df["age"].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64

In [15]:
# age열의 NaN값을 다른 나이 데이터의 평균으로 변경하기
mean_age = df["age"].mean() # age열의 평균 계산(NaN 값 제외)
df["age"] = df["age"].fillna(mean_age)

In [16]:
df["age"].head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: age, dtype: float64

In [17]:
df["embark_town"].loc[825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
830      Cherbourg
Name: embark_town, dtype: object

In [20]:
# embark_town 열의 NaN 값을 최빈값으로 치환하기
most_freq = df["embark_town"].value_counts().idxmax()
most_freq

'Southampton'

In [21]:
df["embark_town"] = df["embark_town"].fillna(most_freq)

In [22]:
df["embark_town"].loc[825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
830      Cherbourg
Name: embark_town, dtype: object

In [23]:
df = sns.load_dataset("titanic")

In [24]:
df["embark_town"].loc[825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
830      Cherbourg
Name: embark_town, dtype: object

In [26]:
# 바로 앞에 있는 행의 값으로 변경하기
df["embark_town"].ffill().loc[825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829     Queenstown
830      Cherbourg
Name: embark_town, dtype: object

In [27]:
df["embark_town"].bfill().loc[825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829      Cherbourg
830      Cherbourg
Name: embark_town, dtype: object

### 누락 데이터가 NaN 으로 표시되지 않는 경우

- 누락 데이터가 NaN이 아닌 0 이나 "-", "?" 같은 값으로 입력되는 경우도 있음
    - 데이터베이스 객체의 replace() 메소드를 활용하여 np.nan 으로 결측처리 해주어야 함

## 중복 데이터 확인

- duplicated()
    - 행의 레코드가 중복되는지 여부를 확인
    - 전에 나온 행들과 비교하여 중복되는 행이면 True를 반환하고 처음 나오는 행은 False를 반환

- 데이터프레임에 duplicated() 메소드를 적용하면 각 행의 중복여부를 나타내는 boolean 시리즈를 반환

In [28]:
# 중복 데이터를 갖는 데이터프레임 만들기
df = pd.DataFrame({"c1" : ["a", "a", "b", "a", "b"],
                   "c2" : [1, 1, 1, 2, 2],
                   "c3" : [1, 1, 2, 2, 2]})

In [29]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [30]:
# 데이터프레임 전체 행 데이터 중에서 중복값 찾기
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [31]:
# 데이터프레임의 특정 열 데이터에서 중복값 찾기
df["c2"].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

## 중복 데이터 제거

- drop_duplicates()
    - 중복되는 행을 제거하고 고유한 관측값을 가진 행들만 유지
 
    - subset 옵션에 열 이름의 리스트를 전달할 수 있음
        - 중복 여부를 판단할 때, subset 옵션에 해당하는 열을 기준으로 판단

In [32]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [34]:
# 데이터프레임에서 중복 행 제거
df.drop_duplicates()

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [35]:
# c2, c3열을 기준으로 중복 행을 제거
df.drop_duplicates(subset = ["c2", "c3"])

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

# 데이터 표준화

- 실무에서 접하는 데이터들은 다양한 곳에서 수집되어 여러가지 원인에 의해 다양한 형태로 표현될 수 있음
    - 단위 선택
    - 대소문자 구분
    - 약칭 활용 등

- 이처럼 동일한 대상을 표현하는 방법에 차이가 있으면 분석의 정확도는 현저하게 낮아짐
    - 데이터 형식을 일관성 있게 표준화 하는 작업이 필요

## 단위 환산

- 같은 데이터셋 안에서는 측정 단위를 동일하게 맞춰줘야함
    - 특히 외국 데이터를 가져오면 국내에서 사용하지 않는 도량형 단위를 사용하는 경우가 많아서 주의가 필요
        - 마일, 야드, 온스 등

In [36]:
df = pd.read_csv("./data/auto-mpg.csv", header = None,
                 names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year",
                          "origin", "name"])

In [37]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [38]:
# mpg(mile per gallon)를 kpl(kilometer per liter)로 변환 (mpg_to_kpl = 0.425)
mpg_to_kpl = 1.60934 / 3.78541
mpg_to_kpl

0.42514285110463595

In [39]:
# mpg 열에 0.425를 곱한 결과를 새로운 열(kpl)에 추가
df["kpl"] = df["mpg"] * mpg_to_kpl

In [40]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.652571
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.802286
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.227428

In [41]:
# kpl열을 소수점 아래 둘째 자리까지 반올림
df["kpl"] = df["kpl"].round(2)

In [42]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.23

## 자료형 변환

- 숫자가 문자열로 저장된 경우에는 숫자형으로 변환해야함
- dtypes 속성을 사용하여 데이터프레임을 구성하는 각 열의 자료형을 확인해야함

In [43]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.23

In [44]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object

In [45]:
# horsepower 열의 고유값 확인
df["horsepower"].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [46]:
print(df["horsepower"].min())
print(df["horsepower"].max())

100.0
?

In [48]:
# 누락 데이터("?") 삭제
df["horsepower"] = df["horsepower"].replace("?", np.nan) # '?'를 np.nan으로 변경
df = df.dropna(subset = "horsepower", axis = 0) # 누락데이터 행을 삭제
df["horsepower"] = df["horsepower"].astype("float") # 문자열을 실수형으로 변환

In [49]:
df["horsepower"].dtypes

dtype('float64')

In [50]:
# 정수형 데이터를 문자형 데이터로 변환
df["origin"] = df["origin"].replace({1 : "USA", 2 : "EU", 3 : "JPN"})

In [51]:
# origin 열의 고유값과 자료형 확인
df["origin"].unique()

array(['USA', 'JPN', 'EU'], dtype=object)

In [52]:
df["origin"].dtypes

dtype('O')

# 범주형 데이터 처리

## 구간 분할

- 데이터 분석 알고리즘에 따라서는 연속 데이터를 일정한 구간으로 나눠서 분석하는 것이 효율적인 경우가 있음
    - 가격, 비용, 효율 등 연속적인 값을 일정한 수준이나 정도를 나타내는 이산값으로 나타내어 구간별 차이를 드러냄
 
- 연속 변수를 일정한 구간으로 나누고 각 구간을 범주형 이산 변수로 변환하는 과정을 구간 분할(binning)이라고 함

In [53]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,USA,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,USA,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,USA,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,USA,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,USA,ford torino,7.23

In [54]:
# 3개의 bin 으로 나누는 경계값의 리스트 구하기
count, bin_dividers = np.histogram(df["horsepower"], bins = 3)

In [55]:
print(count)
print(bin_dividers)

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]

In [56]:
# 3개의 bin에 이름 지정
bin_names = ["저출력", "보통출력", "고출력"]

In [60]:
# 각 데이터를 3개의 bin에 할당
df["hp_bin"] = pd.cut(x = df["horsepower"], # 데이터 배열
                      bins = bin_dividers, # 경계값 리스트
                      labels = bin_names, # bin 이름
                      include_lowest = True) # 첫 경계값 포함

In [61]:
df[["horsepower", "hp_bin"]].head()

   horsepower hp_bin
0       130.0   보통출력
1       165.0   보통출력
2       150.0   보통출력
3       150.0   보통출력
4       140.0   보통출력

In [62]:
df["hp_bin"].value_counts()

hp_bin
저출력     257
보통출력    103
고출력      32
Name: count, dtype: int64

## 더미 변수

- 범주형 데이터를 머신러닝 알고리즘에 바로 사용할 수 없는 경우에는 컴퓨터가 인식 가능한 값으로 변환해야 함

- 이 때 숫자 0 또는 1로 표현되는 더미 변수(dummy variable)를 사용
    - 0과 1은 수의 크고 작음이 아니라 어떤 특성이 있는지 없는지 여부만을 표시
    - 해당 특성이 존재하면 1, 존재하지 않으면 0

- 범주형 데이터를 컴퓨터가 인식할 수 있도록 0과 1로만 구성되는 벡터로 변환하는 것을 원핫인코딩 이라고 부름

In [67]:
# hp_bin 열의 범주형 데이터를 더미 변수로 변환
horsepower_dummies = pd.get_dummies(df["hp_bin"], dtype = "int")

In [68]:
horsepower_dummies.head()

   저출력  보통출력  고출력
0    0     1    0
1    0     1    0
2    0     1    0
3    0     1    0
4    0     1    0

# 정규화

- 각 변수의 상대적 크기 차이 때문에 머신러닝 분석의 결과가 달라질 수 있음
    - 예) 0 ~ 1000 범위의 값을 갖는 변수와 0 ~ 1 범위의 값을 갖는 변수 중 상대적으로 큰 숫자 값을 갖는 변수의 영향이 더 커짐
 
- 숫자 데이터의 상대적인 크기 차이를 제거할 필요가 있음

- 각 열에 속하는 데이터값을 동일한 기준으로 나눈 비율로 나타내는 것을 정규화(normalization)라고 함
    - 일반적으로 데이터의 범위는 0 ~ 1 또는 -1 ~ 1로 정규화
 
- 가장 간단한 정규화 방법은 데이터를 해당 열의 최댓값으로 나누는 방법

In [69]:
df["horsepower"].describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [71]:
# horsepower 열의 최댓값으로 모든 데이터를 나누기
min_max_horsepower = df["horsepower"] / df["horsepower"].max()

In [72]:
min_max_horsepower.describe()

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

- 각 열의 데이터 중에서 최댓값과 최솟값을 뺀 값으로 나누는 방법도 있음
```
(x - min(x)) / (max(x) - min(x))
```

In [73]:
min_x = df["horsepower"] - df["horsepower"].min()
min_max = df["horsepower"].max() - df["horsepower"].min()
min_max_horse = min_x / min_max

In [74]:
min_max_horse.head()

0    0.456522
1    0.646739
2    0.565217
3    0.565217
4    0.510870
Name: horsepower, dtype: float64

In [75]:
min_max_horse.describe()

count    392.000000
mean       0.317768
std        0.209191
min        0.000000
25%        0.157609
50%        0.258152
75%        0.434783
max        1.000000
Name: horsepower, dtype: float64