# 함수 매핑

- 시리즈 또는 데이터프레임의 개별 원소를 특정 함수에 일대일 대응시키는 과정
    - 사용자가 직접 만든 함수를 적용할 수 있기 때문에 판다스 기본 함수로 처리하기 어려운 복잡한 연산을 적용하는 것이 가능

## 개별 원소에 함수 매핑

### 시리즈 원소에 함수 매핑

- 시리즈에 map() 을 적용하면 인자로 전달받는 매핑 함수에 시리즈의 모든 원소를 하나씩 입력하고 리턴값을 받음
    - 시리즈 원소의 개수만큼 리턴값을 받아서 같은 크기의 시리즈 객체로 변환
 
```
Series.map(매핑함수)
```

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "fare"]]
df["ten"] = 10

In [3]:
df.head()

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [4]:
# 10을 더하는 함수
def add_10(n):
    return n + 10

In [5]:
sr1 = df["age"].map(add_10)

In [6]:
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [7]:
sr2 = df["age"].map(lambda n: n + 10)

In [8]:
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

### 데이터프레임 원소에 함수 매핑

In [9]:
df.head()

    age     fare  ten
0  22.0   7.2500   10
1  38.0  71.2833   10
2  26.0   7.9250   10
3  35.0  53.1000   10
4  35.0   8.0500   10

In [10]:
df_map = df.map(lambda x: x + 10)

In [11]:
df_map.head()

    age     fare  ten
0  32.0  17.2500   20
1  48.0  81.2833   20
2  36.0  17.9250   20
3  45.0  63.1000   20
4  45.0  18.0500   20

### 데이터프레임 객체에 함수 매핑

In [16]:
df.iloc[0]

age     22.00
fare     7.25
ten     10.00
Name: 0, dtype: float64

In [15]:
df.apply(lambda x: x["age"] + x["fare"], axis = 1)

0       29.2500
1      109.2833
2       33.9250
3       88.1000
4       43.0500
         ...
886     40.0000
887     49.0000
888         NaN
889     56.0000
890     39.7500
Length: 891, dtype: float64

# 열 분리

- 하나의 열이 여러 가지 정보를 담고 있으면 정보를 분리해야함
    - 예) 어떤 열에 연월일 정보가 있을 때 연, 월, 일을 구분하여 3개의 열로 분리

In [38]:
df = pd.read_excel("./data/주가데이터.xlsx")

In [18]:
df.head()

         연월일   당일종가  전일종가     시가     고가     저가     거래량
0 2018-07-02  10100   600  10850  10900  10000  137977
1 2018-06-29  10700   300  10550  10900   9990  170253
2 2018-06-28  10400   500  10900  10950  10150  155769
3 2018-06-27  10900   100  10800  11050  10500  133548
4 2018-06-26  10800   350  10900  11000  10700   63039

In [19]:
df.dtypes

연월일     datetime64[ns]
당일종가             int64
전일종가             int64
시가               int64
고가               int64
저가               int64
거래량              int64
dtype: object

In [20]:
df.shape

(20, 7)

In [22]:
# 문자열 메소드 사용
df["연월일"] = df["연월일"].astype("str") # 문자열로 자료형 변경

In [23]:
df.dtypes

연월일     object
당일종가     int64
전일종가     int64
시가       int64
고가       int64
저가       int64
거래량      int64
dtype: object

In [25]:
dates = df["연월일"].str.split("-") # 문자열을 split() 메서드로 분리

In [26]:
dates.head()

0    [2018, 07, 02]
1    [2018, 06, 29]
2    [2018, 06, 28]
3    [2018, 06, 27]
4    [2018, 06, 26]
Name: 연월일, dtype: object

In [28]:
df["연"] = dates.str.get(0) # dates 변수의 원소 리스트의 0번째 인덱스 값
df["월"] = dates.str.get(1) # dates 변수의 원소 리스트의 1번째 인덱스 값
df["일"] = dates.str.get(2) # dates 변수의 원소 리스트의 2번째 인덱스 값

In [29]:
df.head()

          연월일   당일종가  전일종가     시가     고가     저가     거래량     연   월   일
0  2018-07-02  10100   600  10850  10900  10000  137977  2018  07  02
1  2018-06-29  10700   300  10550  10900   9990  170253  2018  06  29
2  2018-06-28  10400   500  10900  10950  10150  155769  2018  06  28
3  2018-06-27  10900   100  10800  11050  10500  133548  2018  06  27
4  2018-06-26  10800   350  10900  11000  10700   63039  2018  06  26

In [37]:
# lambda 함수 활용
# df["연월일"].map(lambda x: x[:4])

In [39]:
df.dtypes

연월일     datetime64[ns]
당일종가             int64
전일종가             int64
시가               int64
고가               int64
저가               int64
거래량              int64
dtype: object

In [43]:
# dt메서드 활용
# df["연월일"].dt.day

In [45]:
# lambda, datetime 활용
# df["연월일"].map(lambda x: x.year)

# 필터링

- 시리즈 또는 데이터프레임의 데이터 중에서 특정 조건식을 만족하는 원소만 따로 추출

## 불리언 인덱싱

- 시리즈 객체에 어떤 조건식을 적용하면 각 원소에 대해 참/거짓을 판별하여 불리언 값으로 구성된 시리즈를 반환
- 이때 참에 해당하는 데이터 값을 따로 선택할 수 있음

In [46]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [47]:
titanic["age"] >= 10

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: age, Length: 891, dtype: bool

In [48]:
# age값이 10 이상인 데이터 필터링
titanic.loc[titanic["age"] >= 10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [52]:
# titanic에서 age값이 10이상이면서 20미만인 값들 필터링
df_teenage = titanic.loc[(titanic["age"] >= 10) & (titanic["age"] < 20)]

In [53]:
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [55]:
# age값이 10 미만인 여성 데이터 필터링
df_female_10 = titanic.loc[(titanic["age"] < 10) & (titanic["sex"] == "female")]

In [56]:
df_female_10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [59]:
# age값이 10 미만이거나 60이상인 데이터의 age, sex, alone 컬럼 필터링
df_1060 = titanic.loc[(titanic["age"] < 10) | (titanic["age"] >= 60), ["age", "sex", "alone"]]

In [60]:
df_1060.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

## isin() 메소드 활용

- 데이터프레임의 열에 isin() 메소드를 적용하면 특정 값을 가진 행들을 추출할 수 있음

In [61]:
df_isin = titanic[titanic["sibsp"].isin([3, 4, 5])]

In [62]:
df_isin.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False

# 데이터프레임 합치기

## 데이터프레임 연결

- 서로 다른 데이터프레임들의 구성 형태와 속성이 균일하다면 데이터프레임을 이어 붙여도 데이터의 일관성을 유지할 수 있음

- 기존 데이터프레임의 형태를 유지하면서 이어 붙일 때는 concat() 함수를 활용

In [63]:
df1 = pd.DataFrame({"a" : ["a0", "a1", "a2", "a3"],
                    "b" : ["b0", "b1", "b2", "b3"],
                    "c" : ["c0", "c1", "c2", "c3"]},
                  index = [0, 1, 2, 3])

df2 = pd.DataFrame({"a" : ["a2", "a3", "a4", "a5"],
                    "b" : ["b2", "b3", "b4", "b5"],
                    "c" : ["c2", "c3", "c4", "c5"]},
                  index = [2, 3, 4, 5])

In [64]:
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [65]:
df2

    a   b   c
2  a2  b2  c2
3  a3  b3  c3
4  a4  b4  c4
5  a5  b5  c5

In [66]:
# 2개의 데이터프레임을 행 방향으로 연결
result1 = pd.concat([df1, df2], axis = 0)
result1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
2  a2  b2  c2
3  a3  b3  c3
4  a4  b4  c4
5  a5  b5  c5

In [68]:
# 기존 행 인덱스를 무시하고 새로운 행 인덱스를 설정
result2 = pd.concat([df1, df2], ignore_index = True, axis = 0)
result2

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
4  a2  b2  c2
5  a3  b3  c3
6  a4  b4  c4
7  a5  b5  c5

In [69]:
# 데이터프레임 열 방향 연결
result3 = pd.concat([df1, df2], axis = 1)
result3

     a    b    c    a    b    c
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2
3   a3   b3   c3   a3   b3   c3
4  NaN  NaN  NaN   a4   b4   c4
5  NaN  NaN  NaN   a5   b5   c5

In [70]:
# 연결할 데이터프레임의 교집합을 기준으로 연결
result3_in = pd.concat([df1, df2], axis = 1, join = "inner")
result3_in

    a   b   c   a   b   c
2  a2  b2  c2  a2  b2  c2
3  a3  b3  c3  a3  b3  c3

## 데이터프레임 병합

- merge()
    - SQL의 join 명령어와 비슷한 방식으로 어떤 기준에 의해 두 데이터프레임을 병합하는 개념
        - 병합의 기준이 되는 열이나 인덱스를 키(key)라고 부름
        - 키가 되는 열이나 인덱스는 반드시 양쪽 데이터프레임에 모두 존재해야함

In [2]:
df1 = pd.read_excel("./data/stock price.xlsx")
df2 = pd.read_excel("./data/stock valuation.xlsx")

In [3]:
df1.head()

       id stock_name          value   price
0  128940       한미약품   59385.666667  421000
1  130960     CJ E&M   58540.666667   98900
2  138250      엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280     녹십자엠에스     468.833333   10200

In [10]:
df2.head()

       id     name           eps     bps        per       pbr
0  130960   CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480       하림    274.166667    3551  11.489362  0.887074
2  138040  메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480      이마트  18268.166667  295780  13.931338  0.860437
4  145990      삼양사   5741.000000  108090  14.283226  0.758627

In [8]:
# 데이터프레임 합치기 - 교집합
# on = None : 두 데이터프레임에 공통으로 속하는 모든 열을 기준으로 병합
# how = "inner" : 기준이 되는 열의 데이터가 양쪽 데이터프레임에 공통으로 존재하는 교집합일 경우에만 추출
merge_inner = pd.merge(df1, df2, on = None, how = "inner")
merge_inner

,id,stock_name,value,price,name,eps,bps,per,pbr
0,130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
1,139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
2,145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
3,185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
4,204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

In [11]:
# 데이터프레임 합치기 - 합집합
# on = "id" : "id"열을 키 로 병합
# how = "outer" : 기준이 되는 id열의 데이터가 어느 한 쪽에만 속하더라도 포함
merge_outer = pd.merge(df1, df2, how = "outer", on = "id")
merge_outer

,id,stock_name,value,price,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000.0,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,136480,NaN,NaN,NaN,하림,274.166667,3551.0,11.489362,0.887074
3,138040,NaN,NaN,NaN,메리츠금융지주,2122.333333,14894.0,6.313806,0.899691
4,138250,엔에스쇼핑,14558.666667,13200.0,NaN,NaN,NaN,NaN,NaN
5,139480,이마트,239230.833333,254500.0,이마트,18268.166667,295780.0,13.931338,0.860437
6,142280,녹십자엠에스,468.833333,10200.0,NaN,NaN,NaN,NaN,NaN
7,145990,삼양사,82750.000000,82000.0,삼양사,5741.000000,108090.0,14.283226,0.758627
8,161390,NaN,NaN,NaN,한국타이어,5648.500000,51341.0,7.453306,0.820007
9,181710,NaN,NaN,NaN,NHN엔터테인먼트,2110.166667,78434.0,30.755864,0.827447
10,185750,종근당,40293.666667,100500.0,종근당,3990.333333,40684.0,25.185866,2.470259
11,192400,쿠쿠홀딩스,179204.666667,177500.0,NaN,NaN,NaN,NaN,NaN
12,199800,툴젠,-2514.333333,115400.0,NaN,NaN,NaN,NaN,NaN
13,204210,모두투어리츠,3093.333333,3475.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359
14,207940,NaN,NaN,NaN,삼성바이오로직스,4644.166667,60099.0,89.790059,6.938551

In [13]:
merge_left = pd.merge(df1, df2, how = "left", left_on = "stock_name", right_on = "name")
merge_left

,id_x,stock_name,value,price,id_y,name,eps,bps,per,pbr
0,128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN,NaN
1,130960,CJ E&M,58540.666667,98900,130960.0,CJ E&M,6301.333333,54068.0,15.695091,1.829178
2,138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN,NaN
3,139480,이마트,239230.833333,254500,139480.0,이마트,18268.166667,295780.0,13.931338,0.860437
4,142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN,NaN
5,145990,삼양사,82750.000000,82000,145990.0,삼양사,5741.000000,108090.0,14.283226,0.758627
6,185750,종근당,40293.666667,100500,185750.0,종근당,3990.333333,40684.0,25.185866,2.470259
7,192400,쿠쿠홀딩스,179204.666667,177500,NaN,NaN,NaN,NaN,NaN,NaN
8,199800,툴젠,-2514.333333,115400,NaN,NaN,NaN,NaN,NaN,NaN
9,204210,모두투어리츠,3093.333333,3475,204210.0,모두투어리츠,85.166667,5335.0,40.802348,0.651359

In [14]:
merge_right = pd.merge(df1, df2, how = "right", left_on = "stock_name", right_on = "name")
merge_right

,id_x,stock_name,value,price,id_y,name,eps,bps,per,pbr
0,130960.0,CJ E&M,58540.666667,98900.0,130960,CJ E&M,6301.333333,54068,15.695091,1.829178
1,NaN,NaN,NaN,NaN,136480,하림,274.166667,3551,11.489362,0.887074
2,NaN,NaN,NaN,NaN,138040,메리츠금융지주,2122.333333,14894,6.313806,0.899691
3,139480.0,이마트,239230.833333,254500.0,139480,이마트,18268.166667,295780,13.931338,0.860437
4,145990.0,삼양사,82750.000000,82000.0,145990,삼양사,5741.000000,108090,14.283226,0.758627
5,NaN,NaN,NaN,NaN,161390,한국타이어,5648.500000,51341,7.453306,0.820007
6,NaN,NaN,NaN,NaN,181710,NHN엔터테인먼트,2110.166667,78434,30.755864,0.827447
7,185750.0,종근당,40293.666667,100500.0,185750,종근당,3990.333333,40684,25.185866,2.470259
8,204210.0,모두투어리츠,3093.333333,3475.0,204210,모두투어리츠,85.166667,5335,40.802348,0.651359
9,NaN,NaN,NaN,NaN,207940,삼성바이오로직스,4644.166667,60099,89.790059,6.938551

## 데이터프레임 결합

- join()
    - merge() 함수를 기반으로 만들어져 기본 작동 방식이 비슷하지만 두 데이터프레임의 행 인덱스를 기준으로 결합하는 점이 차이점

In [15]:
df1 = df1.set_index("id")
df2 = df2.set_index("id")

In [16]:
df1.head()

       stock_name          value   price
id
128940       한미약품   59385.666667  421000
130960     CJ E&M   58540.666667   98900
138250      엔에스쇼핑   14558.666667   13200
139480        이마트  239230.833333  254500
142280     녹십자엠에스     468.833333   10200

In [17]:
df2.head()

           name           eps     bps        per       pbr
id
130960   CJ E&M   6301.333333   54068  15.695091  1.829178
136480       하림    274.166667    3551  11.489362  0.887074
138040  메리츠금융지주   2122.333333   14894   6.313806  0.899691
139480      이마트  18268.166667  295780  13.931338  0.860437
145990      삼양사   5741.000000  108090  14.283226  0.758627

In [18]:
df3 = df1.join(df2)
df3

,stock_name,value,price,name,eps,bps,per,pbr
id,,,,,,,,
128940,한미약품,59385.666667,421000,NaN,NaN,NaN,NaN,NaN
130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068.0,15.695091,1.829178
138250,엔에스쇼핑,14558.666667,13200,NaN,NaN,NaN,NaN,NaN
139480,이마트,239230.833333,254500,이마트,18268.166667,295780.0,13.931338,0.860437
142280,녹십자엠에스,468.833333,10200,NaN,NaN,NaN,NaN,NaN
145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090.0,14.283226,0.758627
185750,종근당,40293.666667,100500,종근당,3990.333333,40684.0,25.185866,2.470259
192400,쿠쿠홀딩스,179204.666667,177500,NaN,NaN,NaN,NaN,NaN
199800,툴젠,-2514.333333,115400,NaN,NaN,NaN,NaN,NaN
204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335.0,40.802348,0.651359

In [19]:
df4 = df1.join(df2, how = "inner")
df4

,stock_name,value,price,name,eps,bps,per,pbr
id,,,,,,,,
130960,CJ E&M,58540.666667,98900,CJ E&M,6301.333333,54068,15.695091,1.829178
139480,이마트,239230.833333,254500,이마트,18268.166667,295780,13.931338,0.860437
145990,삼양사,82750.000000,82000,삼양사,5741.000000,108090,14.283226,0.758627
185750,종근당,40293.666667,100500,종근당,3990.333333,40684,25.185866,2.470259
204210,모두투어리츠,3093.333333,3475,모두투어리츠,85.166667,5335,40.802348,0.651359

# 그룹 연산

- 데이터를 특정 기준에 따라 몇 개의 그룹으로 분할하여 처리하는 것

- 데이터를 집계, 변환, 필터링하는데 효율적

- groupby()
    - groupby() 메소드의 처리 과정
        1. 분할 : 데이터를 특정 조건에 의해 분할
        2. 적용 : 데이터를 집계, 변환, 필터링하는데 필요한 메소드 적용
        3. 결합 : 2단계의 처리 결과를 하나로 결합

## 그룹 객체 만들기

### 1개 열을 기준으로 그룹화

In [20]:
titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age", "sex", "class", "fare", "survived"]]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [24]:
df["class"].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [23]:
# class 열을 기준으로 분할
grouped = df.groupby("class", observed = True)
grouped

In [25]:
# 그룹 객체를 iteration 으로 출력
for key, group in grouped:
    print("* key :", key)
    print("* number :", len(group))
    print(group.head())
    print()

* key : First
* number : 216
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1

* key : Second
* number : 184
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1

* key : Third
* number : 491
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [26]:
# 연산 메소드 적용
average = grouped.mean(numeric_only = True)
average

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [27]:
# 개별 그룹 선택하기
group3 = grouped.get_group("Third")
group3.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

### 여러 열을 기준으로 그룹화

In [29]:
# class 열, sex 열을 기준으로 분할
grouped_two = df.groupby(["class", "sex"], observed = True)

In [30]:
# grouped_two 그룹 객체를 iteration 으로 출력
for key, group in grouped_two:
    print("* key :", key)
    print("* number :", group.shape[0])
    print(group.head())
    print()

* key : ('First', 'female')
* number : 94
     age     sex  class      fare  survived
1   38.0  female  First   71.2833         1
3   35.0  female  First   53.1000         1
11  58.0  female  First   26.5500         1
31   NaN  female  First  146.5208         1
52  49.0  female  First   76.7292         1

* key : ('First', 'male')
* number : 122
     age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0
30  40.0  male  First   27.7208         0
34  28.0  male  First   82.1708         0

* key : ('Second', 'female')
* number : 76
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0
43   3.0  female  Second  41.5792         1
53  29.0  female  Second  26.0000         1

* key : ('Second', 'male')
* number : 108
     age   sex   class  fare  survived
17   NaN  male  Second  13.0         1
20  35.0  male  Second  26.0         0
21  34.0  male  Second  13.0         1
33  66.0  male  Second  10.5         0
70  32.0  male  Second  10.5         0

* key : ('Third', 'female')
* number : 144
     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

* key : ('Third', 'male')
* number : 347
     age   sex  class     fare  survived
0   22.0  male  Third   7.2500         0
4   35.0  male  Third   8.0500         0
5    NaN  male  Third   8.4583         0
7    2.0  male  Third  21.0750         0
12  20.0  male  Third   8.0500         0

In [31]:
# grouped_two 그룹 객체에 연산 메소드 적용
average_two = grouped_two.mean()
average_two

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [32]:
type(average_two)

pandas.core.frame.DataFrame

In [33]:
# grouped_two 그룹 객체에서 개별 그룹 선택하기
group3f = grouped_two.get_group(("Third", "female"))
group3f.head()

     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

## 그룹 연산 메소드

### 데이터 집계

- 그룹 객체에 다양한 연산을 적용하는 과정

- 집계 기능을 내장하고 있는 판다스 기본 함수
    - mean()
    - max()
    - min()
    - sum()
    - count()
    - size()
    - var()
    - std()
    - describe()
    - info()
    - first()
    - last()

In [34]:
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [36]:
grouped = df.groupby("class", observed = True)

In [37]:
# 각 그룹에 대한 모든 열의 표준편차를 집계
std_all = grouped.std(numeric_only = True)
std_all

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [38]:
# 각 그룹에 대한 fare 열의 표준편차 집계
std_fare = grouped["fare"].std()
std_fare

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [39]:
# 그룹 객체에 agg() 메소드 적용 - 사용자 정의 함수를 인수로 전달
def min_max(x):
    return x.max() - x.min()

- 집계 연산을 처리하는 사용자 정의 함수를 그룹 객체에 적용하기 위해서는 agg() 메소드를 사용

In [40]:
# 각 그룹의 최댓값과 최솟값의 차이를 계산하여 그룹별 집계
agg_minmax = grouped[["age", "fare", "survived"]].agg(min_max)
agg_minmax

          age      fare  survived
class
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1

- 동시에 여러 개의 함수를 사용하여 각 그룹별 데이터에 대한 집계 연산을 처리
    - 각각의 열에 여러 개의 함수를 일괄 적용할 때는 리스트 형태로 인수를 전달
    - 열마다 다른 종류의 함수를 전달하려면 {열 : 함수} 형태의 딕셔너리를 전달

In [41]:
# 여러 함수를 각 열에 동일하게 적용하여 집계
agg_all = grouped.agg(["min", "max"])
agg_all

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [42]:
# 각 열마다 다른 함수를 적용하여 집계
agg_sep = grouped.agg({"fare" : ["min", "max"], "age" : "mean"})
agg_sep

       fare                  age
        min       max       mean
class
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620

### 그룹 객체 필터링

- 그룹 객체에 filter() 메소드를 적용할 때 조건식을 가진 함수를 전달하여 조건이 참인 그룹만을 필터링

In [43]:
# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
grouped_filter = grouped.filter(lambda x: len(x) >= 200)
grouped_filter

      age     sex  class     fare  survived
0    22.0    male  Third   7.2500         0
1    38.0  female  First  71.2833         1
2    26.0  female  Third   7.9250         1
3    35.0  female  First  53.1000         1
4    35.0    male  Third   8.0500         0
..    ...     ...    ...      ...       ...
885  39.0  female  Third  29.1250         0
887  19.0  female  First  30.0000         1
888   NaN  female  Third  23.4500         0
889  26.0    male  First  30.0000         1
890  32.0    male  Third   7.7500         0

[707 rows x 5 columns]

In [45]:
# second 클래스가 삭제되었음
grouped.count()

        age  sex  fare  survived
class
First   186  216   216       216
Second  173  184   184       184
Third   355  491   491       491

In [46]:
# age 열의 평균이 30보다 작은 그룹만을 필터링하여 데이터프레임으로 반환
age_filter = grouped.filter(lambda x: x["age"].mean() < 30)
age_filter

      age     sex   class     fare  survived
0    22.0    male   Third   7.2500         0
2    26.0  female   Third   7.9250         1
4    35.0    male   Third   8.0500         0
5     NaN    male   Third   8.4583         0
7     2.0    male   Third  21.0750         0
..    ...     ...     ...      ...       ...
884  25.0    male   Third   7.0500         0
885  39.0  female   Third  29.1250         0
886  27.0    male  Second  13.0000         0
888   NaN  female   Third  23.4500         0
890  32.0    male   Third   7.7500         0

[675 rows x 5 columns]

In [47]:
# first 클래스가 삭제되었음
grouped["age"].mean()

class
First     38.233441
Second    29.877630
Third     25.140620
Name: age, dtype: float64

### 그룹 객체에 함수 매핑

- apply() 메소드는 판다스 객체의 개별 원소를 특정 함수에 일대일로 매핑

In [48]:
agg_grouped = grouped.apply(lambda x: x.describe())
agg_grouped

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8152\539340569.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  agg_grouped = grouped.apply(lambda x: x.describe())

                     age        fare    survived
class
First  count  186.000000  216.000000  216.000000
       mean    38.233441   84.154687    0.629630
       std     14.802856   78.380373    0.484026
       min      0.920000    0.000000    0.000000
       25%     27.000000   30.923950    0.000000
       50%     37.000000   60.287500    1.000000
       75%     49.000000   93.500000    1.000000
       max     80.000000  512.329200    1.000000
Second count  173.000000  184.000000  184.000000
       mean    29.877630   20.662183    0.472826
       std     14.001077   13.417399    0.500623
       min      0.670000    0.000000    0.000000
       25%     23.000000   13.000000    0.000000
       50%     29.000000   14.250000    0.000000
       75%     36.000000   26.000000    1.000000
       max     70.000000   73.500000    1.000000
Third  count  355.000000  491.000000  491.000000
       mean    25.140620   13.675550    0.242363
       std     12.495398   11.778142    0.428949
       min      0.420000    0.000000    0.000000
       25%     18.000000    7.750000    0.000000
       50%     24.000000    8.050000    0.000000
       75%     32.000000   15.500000    0.000000
       max     74.000000   69.550000    1.000000

# 멀티 인덱스

- 행 인덱스를 여러 레벨로 구현하는 것

In [49]:
# class열, sex 열을 기준으로 분할
grouped = df.groupby(["class", "sex"])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8152\2940649049.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(["class", "sex"])

In [50]:
gdf = grouped.mean()
gdf

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [51]:
# class 값이 First인 행을 선택하여 출력
gdf.loc["First"]

              age        fare  survived
sex
female  34.611765  106.125798  0.968085
male    41.281386   67.226127  0.368852

In [52]:
gdf.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

In [54]:
# class 값이 First이고, sex값이 female인 행을 선택하여 출력
gdf.loc[("First", "female")]

age          34.611765
fare        106.125798
survived      0.968085
Name: (First, female), dtype: float64

In [57]:
# sex 값이 male인 행을 선택하여 출력
gdf.xs("male", level = "sex")

              age       fare  survived
class
First   41.281386  67.226127  0.368852
Second  30.740707  19.741782  0.157407
Third   26.507589  12.661633  0.135447